name: CI
on: [push]

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64
    - run: ./gradlew build
