name: CI
on: [push]

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker/docker-compose.yml

    steps:
    - uses: actions/checkout@v3
    - run: docker-compose up -d
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64
    - run: ./gradlew build
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run it
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
